services:
  - type: web
    name: af360bank
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .:Comissoes.af360bank:financeiro.af360bank
