services:
  - type: web
    name: af360bank
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python wsgi.py
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
