services:
  - type: web
    name: af360bank
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: af360bank_db
          property: connectionString

databases:
  - name: af360bank_db
    plan: free
    ipAllowList: [] # allow all IPs to connect
